X unit test project
BME-MIT-IET/iet-hf2021-todo-team-name pull request #7
Opened 2021-05-12 08:56 UTC by MrPatesz

Closes #3

2021-05-12 17:08 UTC, npatrik requested changes
These tests were meant to test the behaviour of the Controllers. Instead, they also test the corresponding **Fake**Repositories (which are the copies of the actual Repositories' logic, modified, so they use lists instead of a database), because almost none of the Controller methods contain actual logic, only proxy the call to the Repositories. Therefore the scope of the unit testing should change to testing the actual Repositories with a mock Database.\
Semantics: Quite a lot of tests contain comments does not reflect the testing"phase" in which the commented code block belongs. Most of them can be solved by separating some of the code into Arrange.

2021-05-13 09:31 UTC, mzergi commented on backend/web-api-tests/ClassControllerTest.cs
> +        public async void GetClass_WithNonExistingUser_ThrowsException()
No, one tests for a user that exists in the database, but has no class with the given ID, the other tests for a user that doesn't exist in the DB.

2021-05-13 09:46 UTC, npatrik commented on backend/web-api-tests/ClassControllerTest.cs
> +        public async void GetClass_WithNonExistingUser_ThrowsException()
I understand that the intent for both test is different. Since both have the exact same Act phase, they will function exactly the same. If we expect the controller to always behave deterministically, then it's impossible that both test will pass at the same time, since one expects an exception and the other to return null for the same input.

2021-05-13 10:41 UTC, mzergi commented on backend/web-api-tests/ClassControllerTest.cs
> +        public async void GetClass_WithNonExistingUser_ThrowsException()
I see, fixed.

2021-05-13 10:42 UTC, mzergi commented on backend/web-api-tests/ClassControllerTest.cs
> +            await Assert.ThrowsAsync<ArgumentException>(async () => await controller.GetClass("1"));
That results in compile time error. I removed the result variable and left the function call.

2021-05-13 10:42 UTC, mzergi commented on backend/web-api-tests/ClassControllerTest.cs
> +            await Assert.ThrowsAsync<ArgumentException>(async () => await controller.AddClass(toAdd));
That results in compile time error. I removed the result variable and left the function call.

2021-05-13 10:44 UTC, mzergi commented on backend/web-api-tests/ClassControllerTest.cs
> +            var result = await controller.GetClass("1");
The controller uses the user ID, and the result is used in the assert.

2021-05-13 10:45 UTC, mzergi commented on backend/web-api-tests/ClassControllerTest.cs
> +            var toAdd = new Class() { ID = "10", color = "red", icon = "AUT", name = "onlab", userID = "0" };
Fixed

2021-05-13 10:47 UTC, mzergi commented on backend/web-api-tests/ClassControllerTest.cs
> +            var lengthAfter = controller.GetClasses().Result.Value.Count;
This is a result of the nature of the project. We noted it in the documentation and in comments as well, and we implicitly test the repositories through the controllers. But you are right, in the future we should work on creating unit tests for the individual repositories as well, as well as creating a mock database, so we dont have to resort to fake repositorys, as that is hard to maintain.

2021-05-13 10:56 UTC, mzergi commented on backend/web-api-tests/ClassControllerTest.cs
> +            Assert.Equal(toRemove.ID, result.Value.ID);
Implemented

2021-05-13 10:57 UTC, npatrik commented on backend/web-api-tests/ClassControllerTest.cs
> +            var result = await controller.GetClass("1");
Just to clearify, I only commented on line 197 (for some reason GH shows extra lines). Yes, the result variable was supposed to be used in the assert, but it was not.

2021-05-13 11:24 UTC, npatrik commented on backend/web-api-tests/ClassControllerTest.cs
> +            var lengthAfter = controller.GetClasses().Result.Value.Count;
You probably misunderstood me. Let's forget about the 'controller vs repositories' problem and pretend as if controllers actually had logic and these are valid test for them. Therefore, in this instance, when we try to test the DeleteClass function of the controller, we call it in the Act phase and find proof of the result in the Assert phase. We do this by checking the repository's contents by calling it's appropriate methods and not by asking the controller, like we would do in another request. Yes, technically this works now because the GetClasses just calls the same repository function as we would normally. However, we are now pretending as if controller GetClassses had the actual logic, in which case, by calling it in the Assert we implicitly test that part of the code as well. Instead we should call the mock repository GetClasses, which we guarantee to work as we 'control' it ourselves. You can find an example of this in `Add_AddsItem_ListExpands`.

2021-05-13 11:29 UTC, npatrik commented on doc/unit-testing.md
> +V�g�l ezt is siker�lt kijav�tanunk, �gy m�r ezen tesztek is sikeren lefutottak.
sikeren typo

2021-05-13 12:54 UTC, npatrik commented on backend/web-api-tests/ClassControllerTest.cs
> +            await Assert.ThrowsAsync<ArgumentException>(async () => await controller.GetClass("1"));
Sorry I should have provide an example of the suggested solution:
```
// Act
var result = controller.GetClass("1");

// Assert
await Assert.ThrowsAsync<ArgumentException>(async () => await result);
```
This way, we still get the separated Act and Assert phase. Same for the other two tests.

2021-05-13 17:09 UTC, mzergi commented on backend/web-api-tests/ClassControllerTest.cs
> +            var lengthAfter = controller.GetClasses().Result.Value.Count;
But we are testing the API, which includes the controllers?

2021-05-13 17:14 UTC, mzergi commented on backend/web-api-tests/ClassControllerTest.cs
> +            await Assert.ThrowsAsync<ArgumentException>(async () => await controller.GetClass("1"));
Fixed.

2021-05-13 17:15 UTC, mzergi commented on backend/web-api-tests/ClassControllerTest.cs
> +            var lengthAfter = controller.GetClasses().Result.Value.Count;
And so both methods are OK in this case

2021-05-13 17:17 UTC, mzergi commented on backend/web-api-tests/ClassControllerTest.cs
> +            var lengthAfter = controller.GetClasses().Result.Value.Count;
And actually, here we also test that the controller handles the userID-s well, if we used the repositories we wouldn't test that

2021-05-13 17:20 UTC, mzergi commented on backend/web-api-tests/ClassControllerTest.cs
> +            var lengthAfter = controller.GetClasses().Result.Value.Count;
Implemented using repositories, closing

2021-05-13 17:21 UTC, mzergi commented
Fixed remaining issues as of https://github.com/BME-MIT-IET/iet-hf2021-todo-team-name/pull/7/commits/1164a0e23a746b41c8889689e1fe64cac1914522

2021-05-13 17:52 UTC, MrPatesz commented
Please consider specifying each problem so we can stop this cat and mouse game about problems.

2021-05-13 18:16 UTC, MrPatesz commented
We have tests to ensure correct behaviour of Controllers' getter methods, hence it isn't neccessary to use Repositories instead of Controllers in Assert phases in my opinion.

2021-05-13 18:31 UTC, npatrik approved these changes

2021-05-13 18:33 UTC, npatrik commented
Great work guys, well done. Lots of progress on the project! :rocket:

2021-05-13 18:34 UTC, merged